"""create remaining tables

Revision ID: e1a6bc8e623b
Revises: 
Create Date: 2026-07-05 03:57:53.734961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1a6bc8e623b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repair_reports')
    op.drop_table('diagnoses')
    op.drop_table('technicians')
    op.drop_table('homes')
    op.drop_table('bookings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('technician_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('home_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('issue_title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('issue_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('issue_image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'DIAGNOSED', 'ASSIGNED', 'ON_THE_WAY', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='bookingstatus'), autoincrement=False, nullable=False),
    sa.Column('estimated_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('estimated_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['profiles.id'], name=op.f('bookings_customer_id_fkey')),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], name=op.f('bookings_home_id_fkey')),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], name=op.f('bookings_technician_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    op.create_table('homes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('home_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pincode', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], name=op.f('homes_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('homes_pkey'))
    )
    op.create_table('technicians',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('specialization', postgresql.ENUM('PLUMBER', 'ELECTRICIAN', 'AC', 'APPLIANCE', 'CARPENTER', 'PAINTER', name='technician_specialization'), autoincrement=False, nullable=False),
    sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('technicians_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('technicians_pkey')),
    sa.UniqueConstraint('profile_id', name=op.f('technicians_profile_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('predicted_issue', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('required_tools', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('required_parts', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('diagnoses_booking_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('diagnoses_pkey')),
    sa.UniqueConstraint('booking_id', name=op.f('diagnoses_booking_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('repair_reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('actual_issue', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('repair_steps', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parts_used', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('repair_reports_booking_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('repair_reports_pkey')),
    sa.UniqueConstraint('booking_id', name=op.f('repair_reports_booking_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
